// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Factors;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.3.1810.501 at 00:53 on Wednesday, 17 October 2018.
	/// </remarks>
	public partial class Model_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_numberOfIterations_vdouble__0_vVector__0 has executed. Set this to false to force re-execution of Changed_numberOfIterations_vdouble__0_vVector__0</summary>
		public bool Changed_numberOfIterations_vdouble__0_vVector__0_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isInitialised;
		/// <summary>True if Changed_vdouble__0 has executed. Set this to false to force re-execution of Changed_vdouble__0</summary>
		public bool Changed_vdouble__0_isDone;
		/// <summary>True if Changed_vVector__0 has executed. Set this to false to force re-execution of Changed_vVector__0</summary>
		public bool Changed_vVector__0_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the vdouble__0 property</summary>
		private double[] Vdouble__0;
		public DistributionStructArray<Gaussian,double> vdouble__0_marginal;
		public DistributionStructArray<Gaussian,double> vdouble__1_F;
		/// <summary>Message to marginal of 'vdouble__1'</summary>
		public DistributionStructArray<Gaussian,double> vdouble__1_marginal_F;
		/// <summary>Message to marginal of 'vdouble0'</summary>
		public Gamma vdouble0_marginal_F;
		public DistributionStructArray<Gamma,double> vdouble0_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal<Gamma></summary>
		public Gamma vdouble0_rep_B_toDef;
		/// <summary>The constant 'vGamma0'</summary>
		public Gamma vGamma0;
		/// <summary>Field backing the vVector__0 property</summary>
		private Vector[] VVector__0;
		public PointMass<Vector[]> vVector__0_marginal;
		/// <summary>Message to marginal of 'vVector0'</summary>
		public VectorGaussian vVector0_marginal_F;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vdouble__0'</summary>
		public double[] vdouble__0
		{
			get {
				return this.Vdouble__0;
			}
			set {
				if ((value!=null)&&(value.Length!=23)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+23)+" was expected for variable \'vdouble__0\'");
				}
				this.Vdouble__0 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isInitialised = false;
				this.Changed_numberOfIterations_vdouble__0_vVector__0_isDone = false;
				this.Changed_vdouble__0_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'vVector__0'</summary>
		public Vector[] vVector__0
		{
			get {
				return this.VVector__0;
			}
			set {
				if ((value!=null)&&(value.Length!=23)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+23)+" was expected for variable \'vVector__0\'");
				}
				this.VVector__0 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isInitialised = false;
				this.Changed_numberOfIterations_vdouble__0_vVector__0_isDone = false;
				this.Changed_vVector__0_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of numberOfIterations and vdouble__0 and vVector__0</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_vdouble__0_vVector__0(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_vdouble__0_vVector__0_isDone) {
				return ;
			}
			VectorGaussian vVectorGaussian0 = VectorGaussian.FromNatural(DenseVector.FromArray(new double[2] {0.0, 0.0}), new PositiveDefiniteMatrix(new double[2, 2] {{1.0, 0.0}, {0.0, 1.0}}));
			this.vVector0_marginal_F = ArrayHelper.MakeUniform<VectorGaussian>(vVectorGaussian0);
			VectorGaussian vVector0_rep_F_marginal;
			// Message to 'vVector0_rep' from Replicate factor
			vVector0_rep_F_marginal = ReplicateOp_Divide.MarginalInit<VectorGaussian>(vVectorGaussian0);
			DistributionRefArray<VectorGaussian,Vector> vVector0_rep_F;
			// Create array for 'vVector0_rep' Forwards messages.
			vVector0_rep_F = new DistributionRefArray<VectorGaussian,Vector>(23);
			for(int index0 = 0; index0<23; index0++) {
				vVector0_rep_F[index0] = ArrayHelper.MakeUniform<VectorGaussian>(vVectorGaussian0);
			}
			// Create array for replicates of 'vVector0_rep_F_index0__AMean'
			DenseVector[] vVector0_rep_F_index0__AMean = new DenseVector[23];
			for(int index0 = 0; index0<23; index0++) {
				// Message to 'vdouble__1' from InnerProduct factor
				vVector0_rep_F_index0__AMean[index0] = InnerProductOpBase.AMeanInit(vVector0_rep_F[index0]);
			}
			// Create array for replicates of 'vVector0_rep_F_index0__AVariance'
			PositiveDefiniteMatrix[] vVector0_rep_F_index0__AVariance = new PositiveDefiniteMatrix[23];
			for(int index0 = 0; index0<23; index0++) {
				// Message to 'vdouble__1' from InnerProduct factor
				vVector0_rep_F_index0__AVariance[index0] = InnerProductOpBase.AVarianceInit(vVector0_rep_F[index0]);
			}
			Gamma vdouble0_rep_F_marginal;
			// Message to 'vdouble0_rep' from Replicate factor
			vdouble0_rep_F_marginal = ReplicateOp_Divide.MarginalInit<Gamma>(this.vGamma0);
			DistributionStructArray<Gamma,double> vdouble0_rep_F;
			// Create array for 'vdouble0_rep' Forwards messages.
			vdouble0_rep_F = new DistributionStructArray<Gamma,double>(23);
			for(int index0 = 0; index0<23; index0++) {
				vdouble0_rep_F[index0] = Gamma.Uniform();
			}
			DistributionStructArray<Gaussian,double> vdouble__1_use_B;
			// Create array for 'vdouble__1_use' Backwards messages.
			vdouble__1_use_B = new DistributionStructArray<Gaussian,double>(23);
			for(int index0 = 0; index0<23; index0++) {
				vdouble__1_use_B[index0] = Gaussian.Uniform();
			}
			DistributionRefArray<VectorGaussian,Vector> vVector0_rep_B;
			// Create array for 'vVector0_rep' Backwards messages.
			vVector0_rep_B = new DistributionRefArray<VectorGaussian,Vector>(23);
			for(int index0 = 0; index0<23; index0++) {
				vVector0_rep_B[index0] = ArrayHelper.MakeUniform<VectorGaussian>(vVectorGaussian0);
			}
			VectorGaussian vVector0_rep_B_toDef;
			// Message to 'vVector0_rep' from Replicate factor
			vVector0_rep_B_toDef = ReplicateOp_Divide.ToDefInit<VectorGaussian>(vVectorGaussian0);
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				// Message to 'vdouble0_rep' from Replicate factor
				vdouble0_rep_F_marginal = ReplicateOp_Divide.Marginal<Gamma>(this.vdouble0_rep_B_toDef, this.vGamma0, vdouble0_rep_F_marginal);
				for(int index0 = 0; index0<23; index0++) {
					// Message to 'vdouble0_rep' from Replicate factor
					vdouble0_rep_F[index0] = ReplicateOp_Divide.UsesAverageConditional<Gamma>(this.vdouble0_rep_B[index0], vdouble0_rep_F_marginal, index0, vdouble0_rep_F[index0]);
					// Message to 'vdouble__1_use' from GaussianFromMeanAndVariance factor
					vdouble__1_use_B[index0] = GaussianFromMeanAndVarianceOp.MeanAverageConditional(this.Vdouble__0[index0], this.vdouble__1_F[index0], vdouble0_rep_F[index0]);
					// Message to 'vVector0_rep' from InnerProduct factor
					vVector0_rep_B[index0] = InnerProductOpBase.AAverageConditional(vdouble__1_use_B[index0], this.VVector__0[index0], vVector0_rep_B[index0]);
				}
				// Message to 'vVector0_rep' from Replicate factor
				vVector0_rep_B_toDef = ReplicateOp_Divide.ToDef<VectorGaussian>(vVector0_rep_B, vVector0_rep_B_toDef);
				// Message to 'vVector0_rep' from Replicate factor
				vVector0_rep_F_marginal = ReplicateOp_Divide.Marginal<VectorGaussian>(vVector0_rep_B_toDef, vVectorGaussian0, vVector0_rep_F_marginal);
				for(int index0 = 0; index0<23; index0++) {
					// Message to 'vVector0_rep' from Replicate factor
					vVector0_rep_F[index0] = ReplicateOp_Divide.UsesAverageConditional<VectorGaussian>(vVector0_rep_B[index0], vVector0_rep_F_marginal, index0, vVector0_rep_F[index0]);
					// Message to 'vdouble__1' from InnerProduct factor
					vVector0_rep_F_index0__AVariance[index0] = InnerProductOpBase.AVariance(vVector0_rep_F[index0], vVector0_rep_F_index0__AVariance[index0]);
					// Message to 'vdouble__1' from InnerProduct factor
					vVector0_rep_F_index0__AMean[index0] = InnerProductOpBase.AMean(vVector0_rep_F[index0], vVector0_rep_F_index0__AVariance[index0], vVector0_rep_F_index0__AMean[index0]);
					// Message to 'vdouble__1' from InnerProduct factor
					this.vdouble__1_F[index0] = InnerProductOpBase.InnerProductAverageConditional(vVector0_rep_F_index0__AMean[index0], vVector0_rep_F_index0__AVariance[index0], this.VVector__0[index0]);
					// Message to 'vdouble0_rep' from GaussianFromMeanAndVariance factor
					this.vdouble0_rep_B[index0] = GaussianFromMeanAndVarianceOp.VarianceAverageConditional(this.Vdouble__0[index0], this.vdouble__1_F[index0], vdouble0_rep_F[index0]);
				}
				// Message to 'vdouble0_rep' from Replicate factor
				this.vdouble0_rep_B_toDef = ReplicateOp_Divide.ToDef<Gamma>(this.vdouble0_rep_B, this.vdouble0_rep_B_toDef);
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			// Message to 'vVector0_marginal' from Variable factor
			this.vVector0_marginal_F = VariableOp.MarginalAverageConditional<VectorGaussian>(vVector0_rep_B_toDef, vVectorGaussian0, this.vVector0_marginal_F);
			this.vdouble0_marginal_F = Gamma.Uniform();
			// Message to 'vdouble0_marginal' from Variable factor
			this.vdouble0_marginal_F = VariableOp.MarginalAverageConditional<Gamma>(this.vdouble0_rep_B_toDef, this.vGamma0, this.vdouble0_marginal_F);
			// Create array for 'vdouble__1_marginal' Forwards messages.
			this.vdouble__1_marginal_F = new DistributionStructArray<Gaussian,double>(23);
			for(int index0 = 0; index0<23; index0++) {
				this.vdouble__1_marginal_F[index0] = Gaussian.Uniform();
				// Message to 'vdouble__1_marginal' from DerivedVariable factor
				this.vdouble__1_marginal_F[index0] = DerivedVariableOp.MarginalAverageConditional<Gaussian>(vdouble__1_use_B[index0], this.vdouble__1_F[index0], this.vdouble__1_marginal_F[index0]);
			}
			this.Changed_numberOfIterations_vdouble__0_vVector__0_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to vdouble__0 and vVector__0</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isInitialised)) {
				return ;
			}
			for(int index0 = 0; index0<23; index0++) {
				this.vdouble__1_F[index0] = Gaussian.Uniform();
				this.vdouble0_rep_B[index0] = Gamma.Uniform();
			}
			// Message to 'vdouble0_rep' from Replicate factor
			this.vdouble0_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Gamma>(this.vGamma0);
			this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of vdouble__0</summary>
		private void Changed_vdouble__0()
		{
			if (this.Changed_vdouble__0_isDone) {
				return ;
			}
			this.vdouble__0_marginal = new DistributionStructArray<Gaussian,double>(23, delegate(int index0) {
				return Gaussian.Uniform();
			});
			this.vdouble__0_marginal = Distribution.SetPoint<DistributionStructArray<Gaussian,double>,double[]>(this.vdouble__0_marginal, this.Vdouble__0);
			this.Changed_vdouble__0_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of vVector__0</summary>
		private void Changed_vVector__0()
		{
			if (this.Changed_vVector__0_isDone) {
				return ;
			}
			this.vVector__0_marginal = new PointMass<Vector[]>(this.VVector__0);
			this.Changed_vVector__0_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			// Create array for 'vdouble__1' Forwards messages.
			this.vdouble__1_F = new DistributionStructArray<Gaussian,double>(23);
			this.vGamma0 = Gamma.FromShapeAndRate(1.0, 0.5);
			// Create array for 'vdouble0_rep' Backwards messages.
			this.vdouble0_rep_B = new DistributionStructArray<Gamma,double>(23);
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0_isDone = false;
				}
				this.Changed_numberOfIterations_vdouble__0_vVector__0_isDone = false;
			}
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_vdouble__0_vVector__0(initialise);
			this.Changed_numberOfIterations_vdouble__0_vVector__0(numberOfIterations);
			this.Changed_vVector__0();
			this.Changed_vdouble__0();
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vdouble__0") {
				return this.vdouble__0;
			}
			if (variableName=="vVector__0") {
				return this.vVector__0;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vVector0") {
				return this.VVector0Marginal();
			}
			if (variableName=="vdouble0") {
				return this.Vdouble0Marginal();
			}
			if (variableName=="vdouble__1") {
				return this.Vdouble__1Marginal();
			}
			if (variableName=="vVector__0") {
				return this.VVector__0Marginal();
			}
			if (variableName=="vdouble__0") {
				return this.Vdouble__0Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vdouble__0") {
				this.vdouble__0 = (double[])value;
				return ;
			}
			if (variableName=="vVector__0") {
				this.vVector__0 = (Vector[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble__0' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> Vdouble__0Marginal()
		{
			return this.vdouble__0_marginal;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble__1' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> Vdouble__1Marginal()
		{
			return this.vdouble__1_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble0' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gamma Vdouble0Marginal()
		{
			return this.vdouble0_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector__0' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<Vector[]> VVector__0Marginal()
		{
			return this.vVector__0_marginal;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector0' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public VectorGaussian VVector0Marginal()
		{
			return this.vVector0_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
