// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Factors;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.3.1810.501 at 00:53 on Wednesday, 17 October 2018.
	/// </remarks>
	public partial class Model0_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_vVector3 has executed. Set this to false to force re-execution of Changed_vVector3</summary>
		public bool Changed_vVector3_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vdouble7'</summary>
		public Gamma vdouble7_marginal_F;
		/// <summary>Message to marginal of 'vdouble8'</summary>
		public Gaussian vdouble8_marginal_F;
		/// <summary>Message to marginal of 'vdouble9'</summary>
		public Gaussian vdouble9_marginal_F;
		/// <summary>Field backing the vVector3 property</summary>
		private Vector VVector3;
		public PointMass<Vector> vVector3_marginal;
		/// <summary>Message to marginal of 'vVector4'</summary>
		public VectorGaussian vVector4_marginal_F;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vVector3'</summary>
		public Vector vVector3
		{
			get {
				return this.VVector3;
			}
			set {
				this.VVector3 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vVector3_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of vVector3</summary>
		private void Changed_vVector3()
		{
			if (this.Changed_vVector3_isDone) {
				return ;
			}
			this.vVector3_marginal = new PointMass<Vector>(this.VVector3);
			VectorGaussian vVectorGaussian1 = VectorGaussian.FromNatural(DenseVector.FromArray(new double[2] {1744.7460836769296, 28.704344345898551}), new PositiveDefiniteMatrix(new double[2, 2] {{493071.92980567232, 6968.9399144500667}, {6968.9399144500667, 100.34330885063829}}));
			this.vVector4_marginal_F = ArrayHelper.MakeUniform<VectorGaussian>(vVectorGaussian1);
			VectorGaussian vVector4_use_B = ArrayHelper.MakeUniform<VectorGaussian>(vVectorGaussian1);
			// Message to 'vVector4_marginal' from Variable factor
			this.vVector4_marginal_F = VariableOp.MarginalAverageConditional<VectorGaussian>(vVector4_use_B, vVectorGaussian1, this.vVector4_marginal_F);
			Gamma vGamma1 = Gamma.FromShapeAndRate(12.108571971288066, 52.1993786925916);
			this.vdouble7_marginal_F = Gamma.Uniform();
			Gamma vdouble7_use_B = Gamma.Uniform();
			// Message to 'vdouble7_marginal' from Variable factor
			this.vdouble7_marginal_F = VariableOp.MarginalAverageConditional<Gamma>(vdouble7_use_B, vGamma1, this.vdouble7_marginal_F);
			Gaussian vdouble8_F = default(Gaussian);
			this.vdouble8_marginal_F = Gaussian.Uniform();
			Gaussian vdouble8_use_B = Gaussian.Uniform();
			DenseVector vVector4_use_F_AMean;
			// Message to 'vdouble8' from InnerProduct factor
			vVector4_use_F_AMean = InnerProductOpBase.AMeanInit(vVectorGaussian1);
			PositiveDefiniteMatrix vVector4_use_F_AVariance;
			// Message to 'vdouble8' from InnerProduct factor
			vVector4_use_F_AVariance = InnerProductOpBase.AVarianceInit(vVectorGaussian1);
			// Message to 'vdouble8' from InnerProduct factor
			vVector4_use_F_AVariance = InnerProductOpBase.AVariance(vVectorGaussian1, vVector4_use_F_AVariance);
			// Message to 'vdouble8' from InnerProduct factor
			vVector4_use_F_AMean = InnerProductOpBase.AMean(vVectorGaussian1, vVector4_use_F_AVariance, vVector4_use_F_AMean);
			// Message to 'vdouble8' from InnerProduct factor
			vdouble8_F = InnerProductOpBase.InnerProductAverageConditional(vVector4_use_F_AMean, vVector4_use_F_AVariance, this.VVector3);
			// Message to 'vdouble8_marginal' from DerivedVariable factor
			this.vdouble8_marginal_F = DerivedVariableOp.MarginalAverageConditional<Gaussian>(vdouble8_use_B, vdouble8_F, this.vdouble8_marginal_F);
			Gaussian vdouble9_F = default(Gaussian);
			this.vdouble9_marginal_F = Gaussian.Uniform();
			Gaussian vdouble9_use_B = Gaussian.Uniform();
			// Message to 'vdouble9' from GaussianFromMeanAndVariance factor
			vdouble9_F = GaussianFromMeanAndVarianceOp.SampleAverageConditional(vdouble9_use_B, vdouble8_F, vGamma1);
			// Message to 'vdouble9_marginal' from Variable factor
			this.vdouble9_marginal_F = VariableOp.MarginalAverageConditional<Gaussian>(vdouble9_use_B, vdouble9_F, this.vdouble9_marginal_F);
			this.Changed_vVector3_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			this.Changed_vVector3();
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vVector3") {
				return this.vVector3;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vVector3") {
				return this.VVector3Marginal();
			}
			if (variableName=="vVector4") {
				return this.VVector4Marginal();
			}
			if (variableName=="vdouble7") {
				return this.Vdouble7Marginal();
			}
			if (variableName=="vdouble8") {
				return this.Vdouble8Marginal();
			}
			if (variableName=="vdouble9") {
				return this.Vdouble9Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vVector3") {
				this.vVector3 = (Vector)value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble7' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gamma Vdouble7Marginal()
		{
			return this.vdouble7_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble8' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian Vdouble8Marginal()
		{
			return this.vdouble8_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble9' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian Vdouble9Marginal()
		{
			return this.vdouble9_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector3' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<Vector> VVector3Marginal()
		{
			return this.vVector3_marginal;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector4' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public VectorGaussian VVector4Marginal()
		{
			return this.vVector4_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
